version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_DIR=/app/models
